// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd4__JpytRHS7hpfrVYIlgohISp0AwYQY',
    appId: '1:725606818552:web:0da22788a52217e950910d',
    messagingSenderId: '725606818552',
    projectId: 'todo-8fa95',
    authDomain: 'todo-8fa95.firebaseapp.com',
    storageBucket: 'todo-8fa95.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGqFWUghuroYaxs4Ssja_XGhp4Eln2rlo',
    appId: '1:725606818552:android:45c6f74dec11f0e350910d',
    messagingSenderId: '725606818552',
    projectId: 'todo-8fa95',
    storageBucket: 'todo-8fa95.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB17DqTdThTn8GzaTIHe5qDSCIEkh2O4Bg',
    appId: '1:725606818552:ios:f966c3c3a5724fe150910d',
    messagingSenderId: '725606818552',
    projectId: 'todo-8fa95',
    storageBucket: 'todo-8fa95.firebasestorage.app',
    androidClientId: '725606818552-5dp8bbiumg97ks5okb80jedkiupa1qhc.apps.googleusercontent.com',
    iosClientId: '725606818552-r2l8fkk3cm35m068jiu6n1b4v3kh7398.apps.googleusercontent.com',
    iosBundleId: 'com.example.upTodo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDd4__JpytRHS7hpfrVYIlgohISp0AwYQY',
    appId: '1:725606818552:web:31ce64ce0738e42450910d',
    messagingSenderId: '725606818552',
    projectId: 'todo-8fa95',
    authDomain: 'todo-8fa95.firebaseapp.com',
    storageBucket: 'todo-8fa95.firebasestorage.app',
  );
}
